### ISSUE TITLE
Can someone test Mac compatibility?

### ISSUE THREAD

**Issue by jcaw** [jcaw/theme-magic#11]
I don't have access to a Mac. `pywal`, the engine that drives the theme application, [does work](https://github.com/dylanaraps/pywal/wiki/Installation#Dependencies) on MacOS (using iTerm 2). `theme-magic` should work on MacOS, but I can't test it.

If anyone could test the package on Mac and let me know if it works, it would be most appreciated.

**Comment by alxndrv** [comment]
Tested this on macOS 10.14. 
As far as I can tell, everything works perfectly.
Installed `pywal`, ran `theme-magic-from-emacs`, all iTerm sessions instantly updated to the newly generated colour scheme.

iTerm did go back to its original colour scheme after closing/reopening it, but running `wal -R` also correctly restores the scheme generated by Emacs.

Loving this package, will definitely use it on my Linux machine at home.

**Comment by jcaw** [comment]
Nice! Thanks very much!
